title = "Osteopathie Nöll-Seeger"
baseURL = "https://osteopathie-noell-seeger.de/"
defaultContentLanguage = "de"
theme = "hugo-scroll"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

[params]
  title = "Osteopathie Nöll-Seeger"
  description = "Angelika Nöll-Seeger - Osteopathin, Physiotherapeutin und Heilpraktikerin"
  copyright = "© Angelika Nöll-Seeger"
  favicon = "images/logo.webp"
  images = ["images/logo.webp"]
  hidedesignbyline = true

[params.meta]
  keywords = "osteopathie heilpraktik angelika noell seeger erzhausen"

# This is required for the embedded Google map
[markup.goldmark.renderer]
unsafe = true
